//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1434
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VSXtra.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VSXtra.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown docking style: {0}..
        /// </summary>
        internal static string Attributes_UnknownDockingStyle {
            get {
                return ResourceManager.GetString("Attributes_UnknownDockingStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown relative position: {0}..
        /// </summary>
        internal static string Attributes_UnknownPosition {
            get {
                return ResourceManager.GetString("Attributes_UnknownPosition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MenuCommandHandler type should be defined as a nested type in a type implementing the ICommandGroupProvider markup interface..
        /// </summary>
        internal static string CommandHandler_NoGroupType {
            get {
                return ResourceManager.GetString("CommandHandler_NoGroupType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Package instance for ICommandGroupProvider cannot be obtained..
        /// </summary>
        internal static string CommandHandler_NoPackage {
            get {
                return ResourceManager.GetString("CommandHandler_NoPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ICommandGroupProvider cannot be created..
        /// </summary>
        internal static string CommandHandler_NoProvider {
            get {
                return ResourceManager.GetString("CommandHandler_NoProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown format.
        /// </summary>
        internal static string ExceptionMessageFormat {
            get {
                return ResourceManager.GetString("ExceptionMessageFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported result from QEQS.
        /// </summary>
        internal static string ExceptionMessageQEQS {
            get {
                return ResourceManager.GetString("ExceptionMessageQEQS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported Save flag..
        /// </summary>
        internal static string ExceptionMessageSaveFlag {
            get {
                return ResourceManager.GetString("ExceptionMessageSaveFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expecting an array of size greater than zero..
        /// </summary>
        internal static string General_ArraySizeShouldBeAtLeast1 {
            get {
                return ResourceManager.GetString("General_ArraySizeShouldBeAtLeast1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service &apos;{0}&apos; must be installed for this feature to work.  Ensure that this service is available..
        /// </summary>
        internal static string General_MissingService {
            get {
                return ResourceManager.GetString("General_MissingService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only types implementing IToolbarProvider are accepted in ToolbarAttribute..
        /// </summary>
        internal static string IToolbarProvider_Expected {
            get {
                return ResourceManager.GetString("IToolbarProvider_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only types implementing IUIContextGuidType are accepted in XtraProvideAutoLoad..
        /// </summary>
        internal static string IUIContextGuidType_Expected {
            get {
                return ResourceManager.GetString("IUIContextGuidType_Expected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tool window cannot be created..
        /// </summary>
        internal static string Package_CannotCreateToolWindow {
            get {
                return ResourceManager.GetString("Package_CannotCreateToolWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The service {0} already exists in the service container..
        /// </summary>
        internal static string Package_DuplicateService {
            get {
                return ResourceManager.GetString("Package_DuplicateService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance ID {0} is invalid..
        /// </summary>
        internal static string Package_InvalidInstanceID {
            get {
                return ResourceManager.GetString("Package_InvalidInstanceID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CreateToolWindow only creates Tool Windows derived from ToolWindowPane..
        /// </summary>
        internal static string Package_InvalidToolWindowClass {
            get {
                return ResourceManager.GetString("Package_InvalidToolWindowClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A site has already been set on package {0}..
        /// </summary>
        internal static string Package_SiteAlreadySet {
            get {
                return ResourceManager.GetString("Package_SiteAlreadySet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Package type or package resource not found in the assembly.&gt;.
        /// </summary>
        internal static string PackageNotFound {
            get {
                return ResourceManager.GetString("PackageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Autoload package:         {0}.
        /// </summary>
        internal static string Reg_NotifyAutoLoad {
            get {
                return ResourceManager.GetString("Reg_NotifyAutoLoad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToolWindow:       {0}, {1}.
        /// </summary>
        internal static string Reg_NotifyToolResource {
            get {
                return ResourceManager.GetString("Reg_NotifyToolResource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;Resources type or resource property not found.&gt;.
        /// </summary>
        internal static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The package property of the tool window should only be set by the creator of the tool window..
        /// </summary>
        internal static string ToolWindow_PackageOnlySetByCreator {
            get {
                return ResourceManager.GetString("ToolWindow_PackageOnlySetByCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to toolClsid cannot be added after the Frame is created.\nAdd the toolClsid in the ToolWindow constructor..
        /// </summary>
        internal static string ToolWindow_TooLateToAddTool {
            get {
                return ResourceManager.GetString("ToolWindow_TooLateToAddTool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolbar cannot be added after the Frame is created.\nAdd the ToolBar in the ToolWindow constructor..
        /// </summary>
        internal static string ToolWindow_TooLateToAddToolbar {
            get {
                return ResourceManager.GetString("ToolWindow_TooLateToAddToolbar", resourceCulture);
            }
        }
    }
}
