//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace DeepDiver.UIHierarchyWindow
{
  /// <summary>
  ///   A strongly-typed resource class, for looking up localized strings, etc.
  /// </summary>
  // This class was auto-generated by the StronglyTypedResourceBuilder
  // class via a tool like ResGen or Visual Studio.
  // To add or remove a member, edit your .ResX file then rerun ResGen
  // with the /str option, or rebuild your VS project.
  [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder",
    "2.0.0.0")]
  [DebuggerNonUserCode]
  [CompilerGenerated]
  internal class SHResources
  {
    private static CultureInfo resourceCulture;
    private static ResourceManager resourceMan;

    [SuppressMessage("Microsoft.Performance",
      "CA1811:AvoidUncalledPrivateCode")]
    internal SHResources()
    {
    }

    /// <summary>
    ///   Returns the cached ResourceManager instance used by this class.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Advanced)
    ]
    internal static ResourceManager ResourceManager
    {
      get
      {
        if (ReferenceEquals(resourceMan, null))
        {
          var temp =
            new ResourceManager("DeepDiver.UIHierarchyWindow.SHResources",
                                typeof (SHResources).Assembly);
          resourceMan = temp;
        }
        return resourceMan;
      }
    }

    /// <summary>
    ///   Overrides the current thread's CurrentUICulture property for all
    ///   resource lookups using this strongly typed resource class.
    /// </summary>
    [EditorBrowsable(EditorBrowsableState.Advanced)
    ]
    internal static CultureInfo Culture
    {
      get { return resourceCulture; }
      set { resourceCulture = value; }
    }

    internal static Bitmap SimpleHierarchyImages
    {
      get
      {
        object obj = ResourceManager.GetObject("SimpleHierarchyImages", resourceCulture);
        return ((Bitmap) (obj));
      }
    }
  }
}